hwcomposer: Implement cropping, scaling and transforms
waydroid/android_hardware_waydroid pull request #22
Opened 2022-08-19 00:26 UTC by dos1

HWC is expected to handle buffer cropping (sourceCrop) and destination scaling (displayFrame). This is implemented with Wayland surfaces via wp_viewporter, fixing many issues with popup placement, background handling etc.

HWC is also supposed to handle layer rotation, which is used to implement screen rotation. Wayland has a concept of buffer transform, so use that to fix screen rotation handling with subsurfaces.

2022-08-22 23:15 UTC, aleasto approved these changes

2022-08-25 12:13 UTC, aleasto requested changes
This is broken for me on GRALLOC_DEFAULT

2022-08-25 21:54 UTC, dos1 commented
Is `hwcomposer: Cannot convert hal format to shm format 5` and `wayland-hwc: [destroyed object]: error 0: invalid format 0xffffffea` what you're seeing in logcat with this?

2022-08-25 22:43 UTC, aleasto commented
![Screenshot_20220826_003920](https://user-images.githubusercontent.com/8167495/186780963-607f189e-f62c-4a1b-8dc1-11b749775a1a.png)
You should be able to reproduce with
```
ro.hardware.gralloc=default
ro.hardware.egl=swiftshader
persist.waydroid.use_subsurface=true
```

Also subsurface in general (both multi windows and not) seems to be very crashy on default gralloc, but not caused by this commit

2022-08-26 03:49 UTC, dos1 commented
Hmm, yeah, shm and android buffers aren't being sized correctly. Looks like IWaydroidDisplay interface will have to be extended to also pass other properties of the buffer, as this code has been using layer's display frame to determine buffer size - it's a wonder that it worked as well as it did so far while being this wrong ;)

2022-08-26 05:17 UTC, dos1 commented
I have restricted sourceCrop handling to GBM buffers for now - which means other gralloc implementations are still broken, but they always were and this PR shouldn't make it more visible anymore.

2022-08-26 12:19 UTC, aleasto approved these changes

2022-08-26 12:19 UTC, merged

2022-11-01 14:14 UTC, aleasto commented
This makes mutter (with scaling) unhappy apparently

https://user-images.githubusercontent.com/8167495/199253963-47c31ecc-5a0b-4f35-9f89-e830eba0988d.mp4

2022-11-01 14:43 UTC, dos1 commented
Could you log the values passed to wp_viewport_set_source and wp_viewport_set_destination?

(running Mutter with `WAYLAND_DEBUG=server` or Waydroid via [wlhax](https://git.sr.ht/~kennylevinsen/wlhax) can help to do that without having to patch the code)

2022-11-01 14:59 UTC, aleasto commented
Also happens without scaling actually.

Log looks rather sane to me:
No jumps after releasing the handle.
```
[3805254.678] wp_viewport@50.set_source(2.00000000, 2.00000000, 456.00000000, 625.00000000)
[3805254.692] wp_viewport@50.set_destination(456, 625)
[3805286.276] wp_viewport@50.set_source(2.00000000, 2.00000000, 456.00000000, 625.00000000)
[3805286.292] wp_viewport@50.set_destination(456, 625)
[3805286.995] wp_viewport@50.set_source(2.00000000, 2.00000000, 466.00000000, 633.00000000)
[3805287.010] wp_viewport@50.set_destination(466, 633)
[3805319.934] wp_viewport@50.set_source(2.00000000, 2.00000000, 466.00000000, 633.00000000)
[3805319.973] wp_viewport@50.set_destination(466, 633)
[3805320.510] wp_viewport@50.set_source(2.00000000, 2.00000000, 474.00000000, 639.00000000)
[3805320.530] wp_viewport@50.set_destination(474, 639)
[3805353.704] wp_viewport@50.set_source(2.00000000, 2.00000000, 474.00000000, 639.00000000)
[3805353.721] wp_viewport@50.set_destination(474, 639)
[3805354.228] wp_viewport@50.set_source(2.00000000, 2.00000000, 482.00000000, 641.00000000)
[3805354.242] wp_viewport@50.set_destination(482, 641)
[3805386.861] wp_viewport@50.set_source(2.00000000, 2.00000000, 484.00000000, 641.00000000)
[3805386.878] wp_viewport@50.set_destination(484, 641)
[3805387.411] wp_viewport@50.set_source(2.00000000, 2.00000000, 490.00000000, 641.00000000)
[3805387.422] wp_viewport@50.set_destination(490, 641)
[3805420.913] wp_viewport@50.set_source(2.00000000, 2.00000000, 490.00000000, 641.00000000)
[3805420.926] wp_viewport@50.set_destination(490, 641)
[3805421.399] wp_viewport@50.set_source(2.00000000, 2.00000000, 496.00000000, 647.00000000)
[3805421.410] wp_viewport@50.set_destination(496, 647)
[3805454.828] wp_viewport@50.set_source(2.00000000, 2.00000000, 496.00000000, 647.00000000)
[3805454.845] wp_viewport@50.set_destination(496, 647)
[3805455.415] wp_viewport@50.set_source(2.00000000, 2.00000000, 502.00000000, 649.00000000)
[3805455.434] wp_viewport@50.set_destination(502, 649)
[3805486.010] wp_viewport@50.set_source(2.00000000, 2.00000000, 502.00000000, 649.00000000)
[3805486.031] wp_viewport@50.set_destination(502, 649)
[3805486.622] wp_viewport@50.set_source(2.00000000, 2.00000000, 504.00000000, 651.00000000)
[3805486.640] wp_viewport@50.set_destination(504, 651)
[3805487.219] wp_viewport@50.set_source(2.00000000, 2.00000000, 504.00000000, 653.00000000)
[3805487.233] wp_viewport@50.set_destination(504, 653)
[3805520.024] wp_viewport@50.set_source(2.00000000, 2.00000000, 504.00000000, 653.00000000)
[3805520.050] wp_viewport@50.set_destination(504, 653)
[3805520.591] wp_viewport@50.set_source(2.00000000, 2.00000000, 508.00000000, 655.00000000)
[3805520.608] wp_viewport@50.set_destination(508, 655)
[3805553.761] wp_viewport@50.set_source(2.00000000, 2.00000000, 508.00000000, 655.00000000)
[3805553.773] wp_viewport@50.set_destination(508, 655)
[3805554.763] wp_viewport@50.set_source(2.00000000, 2.00000000, 512.00000000, 655.00000000)
[3805554.781] wp_viewport@50.set_destination(512, 655)
[3805588.002] wp_viewport@50.set_source(2.00000000, 2.00000000, 512.00000000, 655.00000000)
[3805588.018] wp_viewport@50.set_destination(512, 655)
[3805588.526] wp_viewport@50.set_source(2.00000000, 2.00000000, 516.00000000, 655.00000000)
[3805588.543] wp_viewport@50.set_destination(516, 655)
[3805620.525] wp_viewport@50.set_source(2.00000000, 2.00000000, 516.00000000, 655.00000000)
[3805620.545] wp_viewport@50.set_destination(516, 655)
[3805621.017] wp_viewport@50.set_source(2.00000000, 2.00000000, 520.00000000, 657.00000000)
[3805621.028] wp_viewport@50.set_destination(520, 657)
[3805654.935] wp_viewport@50.set_source(2.00000000, 2.00000000, 522.00000000, 657.00000000)
[3805654.965] wp_viewport@50.set_destination(522, 657)
[3805655.414] wp_viewport@50.set_source(2.00000000, 2.00000000, 526.00000000, 657.00000000)
[3805655.425] wp_viewport@50.set_destination(526, 657)
[3805655.818] wp_viewport@50.set_source(2.00000000, 2.00000000, 526.00000000, 657.00000000)
[3805655.828] wp_viewport@50.set_destination(526, 657)
[3805693.115] wp_viewport@50.set_source(2.00000000, 2.00000000, 526.00000000, 657.00000000)
[3805693.131] wp_viewport@50.set_destination(526, 657)
[3805693.633] wp_viewport@50.set_source(2.00000000, 2.00000000, 534.00000000, 661.00000000)
[3805693.644] wp_viewport@50.set_destination(534, 661)
[3805721.046] wp_viewport@50.set_source(2.00000000, 2.00000000, 534.00000000, 661.00000000)
[3805721.109] wp_viewport@50.set_destination(534, 661)
[3805723.537] wp_viewport@50.set_source(2.00000000, 2.00000000, 542.00000000, 665.00000000)
[3805723.570] wp_viewport@50.set_destination(542, 665)
[3805738.034] wp_viewport@50.set_source(2.00000000, 2.00000000, 542.00000000, 665.00000000)
[3805738.054] wp_viewport@50.set_destination(542, 665)
[3805769.791] wp_viewport@50.set_source(2.00000000, 2.00000000, 550.00000000, 669.00000000)
[3805769.807] wp_viewport@50.set_destination(550, 669)
[3805770.995] wp_viewport@50.set_source(2.00000000, 2.00000000, 554.00000000, 669.00000000)
[3805771.012] wp_viewport@50.set_destination(554, 669)
[3805802.709] wp_viewport@50.set_source(2.00000000, 2.00000000, 554.00000000, 669.00000000)
[3805802.719] wp_viewport@50.set_destination(554, 669)
[3805803.379] wp_viewport@50.set_source(2.00000000, 2.00000000, 560.00000000, 677.00000000)
[3805803.397] wp_viewport@50.set_destination(560, 677)
[3805835.228] wp_viewport@50.set_source(2.00000000, 2.00000000, 560.00000000, 677.00000000)
[3805835.249] wp_viewport@50.set_destination(560, 677)
[3805835.666] wp_viewport@50.set_source(2.00000000, 2.00000000, 566.00000000, 677.00000000)
[3805835.675] wp_viewport@50.set_destination(566, 677)
[3805869.788] wp_viewport@50.set_source(2.00000000, 2.00000000, 566.00000000, 677.00000000)
[3805869.931] wp_viewport@50.set_destination(566, 677)
[3805870.382] wp_viewport@50.set_source(2.00000000, 2.00000000, 572.00000000, 679.00000000)
[3805870.389] wp_viewport@50.set_destination(572, 679)
[3805902.829] wp_viewport@50.set_source(2.00000000, 2.00000000, 572.00000000, 679.00000000)
[3805902.845] wp_viewport@50.set_destination(572, 679)
[3805903.314] wp_viewport@50.set_source(2.00000000, 2.00000000, 574.00000000, 681.00000000)
[3805903.325] wp_viewport@50.set_destination(574, 681)
[3805934.692] wp_viewport@50.set_source(2.00000000, 2.00000000, 574.00000000, 681.00000000)
[3805934.705] wp_viewport@50.set_destination(574, 681)
[3805935.544] wp_viewport@50.set_source(2.00000000, 2.00000000, 576.00000000, 685.00000000)
[3805935.564] wp_viewport@50.set_destination(576, 685)
[3805970.291] wp_viewport@50.set_source(2.00000000, 2.00000000, 576.00000000, 685.00000000)
[3805970.309] wp_viewport@50.set_destination(576, 685)
[3805971.016] wp_viewport@50.set_source(2.00000000, 2.00000000, 578.00000000, 685.00000000)
[3805971.027] wp_viewport@50.set_destination(578, 685)
```

And reverting to `create_dmabuf_wl_buffer(pdev->display, buf, width, height, ...)` instead of `drm_handle->height`, `drm_handle->width` makes it work, but `show-full-ui` background image is broken

2022-11-01 16:31 UTC, aleasto commented
If I drag the app out of bounds it starts getting drawn correctly again

2022-11-02 19:08 UTC, aleasto commented
What issues would arise if I disable the viewporter globally until this gets resolved? You stated `many issues with popup placement, background handling etc`

I dislike that mutter went from being arguably the best environment for multi-windows (despite still being a bit of a shitshow) to the worst since this means breaking the biggest pool of existing multi-windows users.

2022-11-02 20:03 UTC, dos1 commented
Misplaced popups, button area being offset in regards to what's displayed, broken wallpaper, etc. Android expects these layers to get cropped.

Could you log `drm_handle->width/height`, `layer->sourceCropi` and `layer->displayFrame`?

2022-11-02 20:20 UTC, aleasto commented
Yea what's interesting is that during the resize the drm_handle buffer size becomes the full screen while the displayFrame is the current window's dimention:

At 1200x800, discarding the cursor, I get:
```
11-02 20:16:41.164    56    56 E hwcomposer: aleasto: drm_handle=441x732, displayFrame=437x728, sourceCropi=437x728
11-02 20:16:41.195    56    56 E hwcomposer: aleasto: drm_handle=441x732, displayFrame=437x728, sourceCropi=437x728
11-02 20:16:41.213    56    56 E hwcomposer: aleasto: drm_handle=441x732, displayFrame=437x728, sourceCropi=437x728
11-02 20:16:41.231    56    56 E hwcomposer: aleasto: drm_handle=1228x828, displayFrame=437x728, sourceCropi=437x728
11-02 20:16:41.247    56    56 E hwcomposer: aleasto: drm_handle=1228x828, displayFrame=437x728, sourceCropi=437x728
11-02 20:16:41.263    56    56 E hwcomposer: aleasto: drm_handle=1228x828, displayFrame=437x728, sourceCropi=437x728
11-02 20:16:41.282    56    56 E hwcomposer: aleasto: drm_handle=1228x828, displayFrame=437x728, sourceCropi=437x728
11-02 20:16:41.299    56    56 E hwcomposer: aleasto: drm_handle=1228x828, displayFrame=451x728, sourceCropi=451x728
11-02 20:16:41.316    56    56 E hwcomposer: aleasto: drm_handle=1228x828, displayFrame=473x728, sourceCropi=473x728
11-02 20:16:41.333    56    56 E hwcomposer: aleasto: drm_handle=1228x828, displayFrame=495x728, sourceCropi=495x728
11-02 20:16:41.349    56    56 E hwcomposer: aleasto: drm_handle=1228x828, displayFrame=505x728, sourceCropi=505x728
11-02 20:16:41.366    56    56 E hwcomposer: aleasto: drm_handle=1228x828, displayFrame=511x728, sourceCropi=511x728
11-02 20:16:41.383    56    56 E hwcomposer: aleasto: drm_handle=1228x828, displayFrame=519x728, sourceCropi=519x728
11-02 20:16:41.399    56    56 E hwcomposer: aleasto: drm_handle=1228x828, displayFrame=525x728, sourceCropi=525x728
11-02 20:16:41.416    56    56 E hwcomposer: aleasto: drm_handle=1228x828, displayFrame=531x728, sourceCropi=531x728
11-02 20:16:41.432    56    56 E hwcomposer: aleasto: drm_handle=1228x828, displayFrame=531x728, sourceCropi=531x728
11-02 20:16:41.449    56    56 E hwcomposer: aleasto: drm_handle=1228x828, displayFrame=549x728, sourceCropi=549x728
11-02 20:16:41.466    56    56 E hwcomposer: aleasto: drm_handle=1228x828, displayFrame=549x728, sourceCropi=549x728
11-02 20:16:41.483    56    56 E hwcomposer: aleasto: drm_handle=1228x828, displayFrame=565x728, sourceCropi=565x728
11-02 20:16:41.500    56    56 E hwcomposer: aleasto: drm_handle=1228x828, displayFrame=571x728, sourceCropi=571x728
11-02 20:16:41.517    56    56 E hwcomposer: aleasto: drm_handle=1228x828, displayFrame=577x728, sourceCropi=577x728
11-02 20:16:41.533    56    56 E hwcomposer: aleasto: drm_handle=1228x828, displayFrame=587x728, sourceCropi=587x728
11-02 20:16:41.550    56    56 E hwcomposer: aleasto: drm_handle=1228x828, displayFrame=595x728, sourceCropi=595x728
11-02 20:16:41.567    56    56 E hwcomposer: aleasto: drm_handle=1228x828, displayFrame=599x728, sourceCropi=599x728
11-02 20:16:41.583    56    56 E hwcomposer: aleasto: drm_handle=1228x828, displayFrame=603x728, sourceCropi=603x728
11-02 20:16:41.600    56    56 E hwcomposer: aleasto: drm_handle=1228x828, displayFrame=609x728, sourceCropi=609x728
11-02 20:16:41.617    56    56 E hwcomposer: aleasto: drm_handle=1228x828, displayFrame=611x728, sourceCropi=611x728
11-02 20:16:41.632    56    56 E hwcomposer: aleasto: drm_handle=1228x828, displayFrame=611x728, sourceCropi=611x728
11-02 20:16:41.649    56    56 E hwcomposer: aleasto: drm_handle=1228x828, displayFrame=613x728, sourceCropi=613x728
11-02 20:16:41.666    56    56 E hwcomposer: aleasto: drm_handle=1228x828, displayFrame=613x728, sourceCropi=613x728
11-02 20:16:41.697    56    56 E hwcomposer: aleasto: drm_handle=1228x828, displayFrame=613x728, sourceCropi=613x728
11-02 20:16:41.709    56    56 E hwcomposer: aleasto: drm_handle=1228x828, displayFrame=615x728, sourceCropi=615x728
11-02 20:16:41.726    56    56 E hwcomposer: aleasto: drm_handle=1228x828, displayFrame=615x728, sourceCropi=615x728
11-02 20:16:41.742    56    56 E hwcomposer: aleasto: drm_handle=1228x828, displayFrame=615x728, sourceCropi=615x728
11-02 20:16:41.759    56    56 E hwcomposer: aleasto: drm_handle=1228x828, displayFrame=615x728, sourceCropi=615x728
11-02 20:16:41.775    56    56 E hwcomposer: aleasto: drm_handle=1228x828, displayFrame=615x728, sourceCropi=615x728
11-02 20:16:41.794    56    56 E hwcomposer: aleasto: drm_handle=1228x828, displayFrame=615x728, sourceCropi=615x728
11-02 20:16:41.811    56    56 E hwcomposer: aleasto: drm_handle=619x732, displayFrame=615x728, sourceCropi=615x728
11-02 20:16:41.828    56    56 E hwcomposer: aleasto: drm_handle=619x732, displayFrame=615x728, sourceCropi=615x728
11-02 20:16:41.844    56    56 E hwcomposer: aleasto: drm_handle=619x732, displayFrame=615x728, sourceCropi=615x728
```

2022-11-02 20:30 UTC, dos1 commented
Hmm... does it behave the same way under Weston?

2022-11-02 20:53 UTC, aleasto commented
Not at all.
weston does have some artifacts but they happen without cropping as well.
kwin and wlroots are perfectly happy.

https://user-images.githubusercontent.com/8167495/199600303-aed50788-76d4-4843-8c2b-6aa24a6d38fb.mp4

2022-11-02 21:01 UTC, dos1 commented
Which version of Mutter are you running it on? You mentioned "(with scaling)", did you mean hidpi scaling? What's the display configuration you're seeing it on?

I'm going to try to reproduce and take a closer look at it tomorrow.

2022-11-02 21:11 UTC, aleasto commented
Mutter 42.5
I tried both on a new tty where it automatically picked a hidpi scaling of 2x, and nested where it launched without hidpi scaling. The effect is the same in both cases.

2022-11-04 22:08 UTC, dos1 commented
Looks like a bug in Mutter, which gets confused by Waydroid attaching a buffer with different size, but then setting the exact same viewporter values. Seems like Mutter retains the old state even though its context has changed because of different buffer being attached.

It may be workaroundable by destroying and recreating the whole viewporter object at each commit.

2022-11-04 22:10 UTC, aleasto commented
> Seems like Mutter retains the old state even though its context has changed because of different buffer being attached.

That was my intuition as well.

> It may be workaroundable by destroying and recreating the whole viewporter object at each commit.

Well i can try that.. :)

2022-11-04 22:38 UTC, dos1 commented
Hmm, looking closer at Mutter's code, I think it's unlikely that recreating the viewporter object will help (still worth trying though, it's a pretty complex codebase) - but moving viewporter calls to after wl_surface_attach might.

2022-11-04 22:40 UTC, aleasto commented
Including `wp_viewporter_get_viewport` ?

2022-11-04 22:42 UTC, aleasto commented
I remember trying that already actually. Except indeed `wp_viewporter_get_viewport`

2022-11-04 23:22 UTC, dos1 commented
So yeah, this makes Mutter work fine:

```diff
diff --git a/src/compositor/meta-shaped-texture.c b/src/compositor/meta-shaped-texture.c
index b3e087af9a64..892567c98303 100644
--- a/src/compositor/meta-shaped-texture.c
+++ b/src/compositor/meta-shaped-texture.c
@@ -146,6 +146,8 @@ meta_shaped_texture_init (MetaShapedTexture *stex)
   stex->transform = META_MONITOR_TRANSFORM_NORMAL;
 }
 
+static void meta_shaped_texture_reset_pipelines (MetaShapedTexture *stex);
+
 static void
 update_size (MetaShapedTexture *stex)
 {
@@ -195,12 +197,13 @@ update_size (MetaShapedTexture *stex)
 
   stex->size_invalid = FALSE;
 
-  if (stex->dst_width != dst_width ||
+  if (true || stex->dst_width != dst_width ||
       stex->dst_height != dst_height)
     {
       stex->dst_width = dst_width;
       stex->dst_height = dst_height;
       meta_shaped_texture_set_mask_texture (stex, NULL);
+      meta_shaped_texture_reset_pipelines (stex);
       clutter_content_invalidate_size (CLUTTER_CONTENT (stex));
       g_signal_emit (stex, signals[SIZE_CHANGED], 0);
     }
```

I'll need to replace that `true` with a check for the new buffer size being different than the old one - but that's something for tomorrow.

2022-11-05 21:11 UTC, dos1 commented
Turned out to be simpler than that: https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/2689

2022-11-05 21:31 UTC, aleasto commented
Cool! Thank you